<footer class="footer-distributed">

			<div class="footer-left">

				<h3>Harsha Vardhan Manoj Bikki</h3>

				<p class="footer-links">
					<a href="#">Home</a>
			
				
				
					<a href="#">Project</a>
				
		
					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">harshavardhanmanoj &copy; 2017</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>377 Avon Rd</span> Devon ,PA ,USA</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+1 (484)-557-7167</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:harshavardhanmanoj47@gmail.com">harshavardhanmanoj47@gmail.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					
					I am a graduate student currently persuing masters in computer science.
				</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
				

				</div>

			</div>

		</footer>