    <h1>Harsha Vardhan Manoj</h1>
    <h2>Programmer / Developer / Student</h2>
  <ol>
  <li><a class="active" href="#home">Home</a></li>
  <li><a href="#news">Projects</a></li>
  <li><a href="#contact">Contact</a></li>
</ol>
<br>

  <svg height="10%" width="95%">
  <line x1="5%" y1="2%" x2="100%" y2="2%" style="stroke:black;stroke-width:4" />
</svg>
<div class="icon-bar">
  <a href="#" class="facebook"><i class="fa fa-facebook"></i></a> 
  <a href="#" class="twitter"><i class="fa fa-twitter"></i></a> 
  <a href="#" class="google"><i class="fa fa-google"></i></a> 
  <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
  <a href="#" class="youtube"><i class="fa fa-youtube"></i></a> 
</div>

 <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

