                                     <ul>
<li><a href="Resume_.pdf" target="_blank" class="round-button" >MyResume</a></li>
<li><a href="#" class="round-button1" >MY work</a></li>
   </ul>
   
   <img class="lazy" src="Myimg.jpg">  
   
   <div id="matter">
   <p id="hello">Hello, </p>
   <br/>
   <br/>
     <p id="mat" >
       This is manoj this page helps you to know more about me.
     </p>
   
   
   </div>