 <br>
<p id="proj1">LATEST PROJECTS</p>

<br><br>
  <svg height="10%" width="95%">
  <line x1="5%" y1="2%" x2="100%" y2="2%" style="stroke:black;stroke-width:2" />
</svg>
  <div class="round-button2" >Proj-1</div>
  <img src="crash1.jpg" class="imgcra">
     <p class="heightext">Vehicle Accident Detection</p>
     
     <p class="insidetext">The Vehicular Accident Detection System primarily detects various obstacles in the surroundings of the vehicle,
      processes it using raspberry pi, and displays meaningful information to the user.</p>
      
      <a href="pdf1.pdf" target="_blank"> <img src="pdf.png" class="pdf"></a>
       <a href="word1.docx" target="_blank"> <img src="word.png" class="word"></a>
       <p id="post1"> Poster </p>
       <p id="doc1">Project document</p>
 <br>
 <br>
 <svg height="10%" width="95%">
  <line x1="5%" y1="2%" x2="100%" y2="2%" style="stroke:black;stroke-width:2" />
</svg>
<br>
<br>
  <div class="round-button2" >Proj-2</div>
  <img src="cow3.jpg" class="imgcra">
     <p class="heightext1">Vehicle Monitoring System using the Internet of Things</p>
     
     <p class="insidetext1">In this modern and fast moving world, it has become a basic ne-cessity to be constantly aware of
      youngster`s safety. When young-sters are just eligible to drive, it is important to keep monitoring their driving to where they
       are going and at what speed. Therefore,parents might put constraints to where they should go and at what speed by notifying
        them periodically. In this work, we plan to develop a vehicle event monitoring system using IoT Technologies. Along with
         tracking of various events related to driving, we would also develop an emergency/panic button and install fire sensor in the
      car which would send an emergency message to the parent`s mobile number and relevant ERTs during abnormal situation.</p>
      
      <a href="pdf2.pdf" target="_blank"> <img src="pdf.png" class="pdf1"></a>
       <a href="pdf3.docx" target="_blank"> <img src="pdf.png" class="word1"></a>
       <p id="post2"> Poster </p>
       <p id="doc2">Project document</p>
  
    <br>
 <br>
 <br>
<br>
    <br>
 <br>
 <br>
<br>
    <br>
 <br>
 
 <svg height="10%" width="95%">
  <line x1="5%" y1="2%" x2="100%" y2="2%" style="stroke:black;stroke-width:2" />
</svg>

 <div class="gallerycontainer">

<a class="thumbnail" href="#thumb"><img src="img1.jpg" width="100px" height="66px" border="0" /><span><img src="img1.jpg" /></span></a>

<a class="thumbnail" href="#thumb"><img src="img2.jpg" width="100px" height="66px" border="0" /><span><img src="img2.jpg" /></span></a>
  <a class="thumbnail" href="#thumb"><img src="img3.jpg" width="100px" height="75px" border="0" /><span><img src="img3.jpg" /></span></a> 

<a class="thumbnail" href="#thumb"><img src="img4.jpg" width="100px" height="70px" border="0" /><span><img src="img4.jpg" /></span></a>
<a class="thumbnail" href="#thumb"><img src="img5.jpg" width="100px" height="75px" border="0" /><span><img src="img5.jpg" /></span></a> 

</div>

<p id="others">Other Details.</p>
 <p id="matter">I play Volleyball I am a foodie and  moderate painter and love watching movies
   and spending time with friend and finally I love travelling.</p>

  <br>
<br>
    <br>
 <br>
 
 <svg height="10%" width="95%">
  <line x1="5%" y1="2%" x2="100%" y2="2%" style="stroke:black;stroke-width:2" />
</svg>

 <p id="contt">Contact me for more info >>></p>
<a href="#" style=" text-decoration: none;"><div class="round-button3" >Contact</div></a>
